### PR TITLE
Misc updates

### PR DESCRIPTION
**Pull request by natalan**
- Use ES6 class
- Switch to 'ping' module (thanks MeFisto94 for initial PR #7)
- Add optional `showDisconnectedLog` property
- Update tests

### CODE REVIEW

**Comment by piotrtobolski** [comment]
@natalan I spent few hours investigating why my TV has wrong ON status in homebridge. This PR broke all apps checking for TV power status. Previously method isAlive was calling callback with err, and now it is calling it with power status so it is the opposite. Breaking changes like this one should be in major releases. All packages I've seen were using `samsung-remote` with caret syntax, e.g. ^1.2.5 that does upgrate this package to 1.x.x

**Comment by natalan** [comment]
@piotr-tobolski thanks for reporting this. Clearly a typo on my end that should have been tested. I'll make a commit to fix the conditional logic.

**Comment by natalan** [comment]
@piotr-tobolski should be fixed in 1.4.1

**Comment by piotrtobolski** [comment]
@natalan Thank you!

**Pull request merged**
